### ISSUE TITLE
Support of SCSS

### ISSUE THREAD

**Issue by olignyf** [dferber90/jest-transform-css#10]
Hi,
I am trying to do visual snapshot testing, with SCSS and @import. I don't find any way to do it. I tried both "sass-jest" and "sass-jest-transform" but they fail in my case. I am thinking that a valid solution would be to edit this project "jest-transform-css" to include support for SCSS? Would you be interested in a pull-request? 
Thanks

**Comment by dferber90** [comment]
Maybe a separate project would be better to avoid making this one solve too many problems at once. 

This project was the result of me diving into visual regression testing, but my main takeaway was that it's better to use a SaaS solution like https://percy.io/. That's why I don't really use this project anymore, so I'm not very motivated to maintain it. Hope that is understandable!

**Comment by olignyf** [comment]
Thanks for the follow-up !

**Comment by PrestonII** [comment]
Hi !  Was a separate project created for this @olignyf ?

I'm facing a similar and would love to use/contribute to the solution

**Comment by olignyf** [comment]
> Hi ! Was a separate project created for this @olignyf ?
> 
> I'm facing a similar and would love to use/contribute to the solution

Yes I created https://github.com/olignyf/jest-transform-scss
It works well with various import types (from local and npm modules)

**Comment by dferber90** [comment]
Awesome, I'll close this then :)
