### ISSUE TITLE
Unclear if css has been transformed

### ISSUE THREAD

**Issue by frmysantana** [dferber90/jest-transform-css#9]
I've tried to configure my project to use jest-transform-css as per the documentation, but as far as I can tell, the css is not loading in at all. 

My project uses React and imports basic css stylesheets which are usually injected into the webpage inside style elements via webpack. My webpack config uses css-loader and style-loader but no explicit mention of PostCSS. 

Console logging the document in my tests shows me the markup of my react components, but no sign of styles. Not sure if I did this incorrectly or am just not looking at it in the right way. How are the styles supposed to be outputted? Should I be expecting it to be in the head in a style element, a style element inside the body, or maybe something else?

My jest config is (it is part of my package.json):
```javascript
"jest": {
    "rootDir": "./src",
    "transform": {
      "^.+\\.js$": "babel-jest",
      "^.+\\.css$": "jest-transform-css"
    },
    "setupFiles": [
      "<rootDir>/test/setEnvVars.js"
    ]
  }
```

This is the css part of my webpack config:
```javascript
module: {
      rules: [
        {
          test: /\.css$/,
          use: [
            'style-loader',
            'css-loader'
          ]
        },
        {
          test: /\.(png|svg|jpg|gif|woff)$/,
          use: [
            'file-loader'
          ]
        },
        {
          test: /\.(js|jsx)$/,
          exclude: /(node_modules)/,
          loader: 'babel-loader',
          options: { presets: ['@babel/env'] }
        }
      ]
    },
```

Let me know if there's any other information that is needed.

**Comment by dferber90** [comment]
You can check out this example to see how it should behave: https://github.com/dferber90/visual-regression-testing-example

Your webpack config should be unrelated as it is not applied when jest runs. Your config looks good to me, but it's been quite a while since I last worked on this project.

Maybe you're missing this file https://github.com/dferber90/visual-regression-testing-example/blob/master/jesttransformcss.config.js, but that's only relevant if you're using css modules.
